# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: apollo
      POSTGRES_PASSWORD: apollo
    ports:
      - '6543:5432'
